[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$5nzvPcc4hxBiLGXMOQcgpA$sQGDKGst7XlD36389WmnBBdahWRCCY0pVJVGcIYek62e.zxXHSYjhJmdKtaCx8tFFTkCwmcUjqXyfDvKNJO6LQ

