[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$vHfOGSPEGCMkBEDIeY/R2g$X5WD1H2DRRCmaaNZ7KOn8fv2je4QEP8NEX6cXuG9fgGDagRw2wGZD1LbkSakV5XFD/ZjKDsRpQCwwMbhByF6pw

